baseURL = "https://www.defichain.com/"
googleAnalytics = ""
languageCode = "en-us"
title = "DeFi Blockchain"

[params]
  uen = "201918368M"
  [params.github]
    label = "GitHub"
    url = "https://github.com/DeFiCh/ain"
    releases_url = "https://github.com/DeFiCh/ain/releases"
  [params.social]
    facebook = "https://facebook.com/cakedefi/"
    twitter = "https://twitter.com/cakedefi"
    reddit = "https://reddit.com/r/cakedefi/"
    youtube = "https://www.youtube.com/channel/UCkRa0RHkJ9Udd_mVWl8fa8A"
    telegram = "https://t.me/CakeDeFi_EN"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[blackfriday]
  extensions = ["hardLineBreak"]

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    title = "DeFi Blockchain"
    description = "Decentralized finance enabled."
    company_name = "DeFi Blockchain"
    copyright = "All Rights Reserved"
    weight = 20
  # [languages.de]
  #   languageName = "Deutsch"
  #   title = "DeFi Blockchain"
  #   description = "Making the world a brighter place"
  #   company_name = "Cake Pte. Ltd."
  #   copyright = "Alle Rechte vorbehalten"
  #   fast_track = "Fast-track"
  #   weight = 30
